# Generated by Django 5.2.7 on 2025-11-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_area_concurso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
