# Generated by Django 5.2.8 on 2025-11-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_numero_edital_concurso_numedital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='edital_pdf',
            field=models.FileField(blank=True, null=True, upload_to='editais/', verbose_name='Edital PDF'),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='formulario',
            field=models.FileField(blank=True, null=True, upload_to='formularios/', verbose_name='Formulário'),
        ),
    ]
