# Generated by Django 5.2.8 on 2025-11-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_concurso_edital_pdf_alter_concurso_formulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='documento',
        ),
        migrations.RenameField(
            model_name='concurso',
            old_name='numEdital',
            new_name='numero_edital',
        ),
        migrations.RemoveField(
            model_name='concurso',
            name='email',
        ),
        migrations.RemoveField(
            model_name='concurso',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='concurso',
            name='edital_pdf',
            field=models.FileField(blank=True, null=True, upload_to='editais/', verbose_name='Edital Completo (PDF)'),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='formulario',
            field=models.FileField(blank=True, null=True, upload_to='formularios/', verbose_name='Formulário de Inscrição'),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='situacao_manual',
            field=models.CharField(blank=True, choices=[('', '— Automático —'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado'), ('PRORROGADO', 'Prorrogado'), ('ADIADO', 'Adiado'), ('FINALIZADO', 'Finalizado')], default='', help_text='Se definido, substitui o status automático calculado pelas datas.', max_length=20, verbose_name='Situação Manual'),
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
