# Generated by Django 5.2.7 on 2025-10-31 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Concurso')),
                ('numero_edital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Edital')),
                ('orgao', models.CharField(max_length=255, verbose_name='Órgão/Entidade Responsável')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo/Área de Atuação')),
                ('numero_vagas', models.PositiveIntegerField(default=1, verbose_name='Número de Vagas')),
                ('requisitos', models.TextField(blank=True, null=True, verbose_name='Requisitos Básicos')),
                ('local_atuacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de Atuação')),
                ('remuneracao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remuneração (R$)')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('inicio_inscricoes', models.DateField(blank=True, null=True, verbose_name='Início das Inscrições')),
                ('fim_inscricoes', models.DateField(blank=True, null=True, verbose_name='Término das Inscrições')),
                ('data_prova', models.DateField(blank=True, null=True, verbose_name='Data da Prova')),
                ('prazo_recursos', models.DateField(blank=True, null=True, verbose_name='Prazo para Recursos')),
                ('previsao_resultado', models.DateField(blank=True, null=True, verbose_name='Previsão de Resultado')),
                ('edital_pdf', models.FileField(blank=True, null=True, upload_to='editais/', verbose_name='Edital Completo (PDF)')),
                ('formulario', models.FileField(blank=True, null=True, upload_to='formularios/', verbose_name='Formulário de Inscrição')),
                ('modelo_documento', models.FileField(blank=True, null=True, upload_to='modelos/', verbose_name='Modelo de Documento')),
                ('situacao_manual', models.CharField(blank=True, choices=[('', '— Automático —'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado'), ('PRORROGADO', 'Prorrogado'), ('ADIADO', 'Adiado'), ('FINALIZADO', 'Finalizado')], default='', help_text='Se definido, substitui o status automático calculado pelas datas.', max_length=20, verbose_name='Situação Manual')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concursos', to='app.area')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concursos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concurso / Processo Seletivo',
                'verbose_name_plural': 'Concursos e Processos Seletivos',
                'ordering': ['-data_publicacao', 'titulo'],
            },
        ),
    ]
