# Generated by Django 5.2.8 on 2025-11-08 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concurso',
            old_name='numero_edital',
            new_name='numEdital',
        ),
        migrations.AddField(
            model_name='concurso',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='concurso',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='situacao_manual',
            field=models.CharField(blank=True, choices=[('', '— Automático —'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado'), ('PRORROGADO', 'Prorrogado'), ('ADIADO', 'Adiado'), ('FINALIZADO', 'Finalizado')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.concurso')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.documento')),
            ],
        ),
    ]
